version: '3'
services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        user: "1000:1000"
        networks:
            - app-network

    web:
        image: nginx:1.21-alpine
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: freemarket-mysql
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - app-network

    mailpit:
        image: axllent/mailpit:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
