services:
    # Nginx Webサーバー
    nginx:
        image: nginx:1.21.1
        ports:
        - "80:80"  # ホストの80番ポートをコンテナの80番にマッピング
        volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./src:/var/www/html  # Laravelアプリケーションのコードをマウント
        depends_on:
        - php
        networks:
        - app-network

    # PHP-FPMコンテナ
    php:
        build: ./docker/php
        volumes:
        - ./src:/var/www/html
        networks:
        - app-network

    # MySQLデータベース
    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - mysql-data:/var/lib/mysql
        networks:
        - app-network

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: laravel_user
            PMA_PASSWORD: password
        ports:
        - "8080:80"  # ホストの8080番ポートをphpMyAdminの80番にマッピング
        depends_on:
        - mysql
        networks:
        - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local

